h100:
- 'h100-cr_0'
- 'h100-cr_1'
- 'h100-cw_0'
- 'h100-cw_1'
h200:
- 'h200-cw_0'
- 'h200-cw_1'
- 'h200-nb_0'
- 'h200-nb_1'
- 'h200-nb_2'
- 'h200-nb_3'
- 'h200-nv_0'
- 'h200-nv_1'
- 'h200-nv_2'
- 'h200-nv_3'
b200-trt:
- 'b200-nv_0'
- 'b200-nv_1'
- 'b200-nb_0'
- 'b200-nb_1'
b200:
# Docker-only nodes
- 'b200-dgxc_1'
- 'b200-dgxc_2'
# Slurm nodes (also have b200 label, can run docker workloads)
- 'b200-nv_0'
- 'b200-nv_1'
- 'b200-nb_0'
- 'b200-nb_1'
mi300x:
- 'mi300x-amd_0'
- 'mi300x-amd_1'
- 'mi300x-amd_2'
- 'mi300x-amd_3'
- 'mi300x-amd_4'
- 'mi300x-cr_0'
- 'mi300x-amds_0'
- 'mi300x-amds_1'
- 'mi300x-amds_2'
- 'mi300x-amds_3'
mi325x:
- 'mi325x-amd_0'
- 'mi325x-amd_1'
- 'mi325x-amd_2'
- 'mi325x-amd_3'
mi355x:
- 'mi355x-amd_0'
- 'mi355x-amd_1'
- 'mi355x-amd_2'
- 'mi355x-amd_3'
gb200:
- gb200-nv_0
