name: Template - Collect Results

on:
  workflow_call:
    inputs:
      exp-name:
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  collect-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Download JSON artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: results/
          pattern: ${{ inputs.exp-name && format('{0}_*', inputs.exp-name) || '*' }}

      - name: Print summary
        run: |
          pip install tabulate
          python3 utils/summarize.py results/ >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.exp-name || 'all' }}

      - name: Upload aggregated results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: results_${{ inputs.exp-name || 'all' }}
          path: agg_${{ inputs.exp-name || 'all' }}.json
